# Generated by Django 5.0.7 on 2024-07-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_remove_post_like_num_post_like_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_num',
        ),
        migrations.AddField(
            model_name='post',
            name='like_num',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
