# Generated by Django 5.0.7 on 2024-07-16 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_post_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
    ]
