# Generated by Django 5.0.7 on 2024-07-16 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_post_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='writer',
        ),
    ]
